### PR TITLE
Update brand assets

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Chore, updates Astro logo to align with rebrand
- Adds changeset to release new version of VS Code extension

## Testing

N/A

## Docs

N/A

### CODE REVIEW

**Review by ematipico — APPROVED** [review]

**Comment by natemoo-re** [comment]
> lgtm, except the svgs aren't rendering for me?

Yep, good catch. Just fixed that!

**Review by jasikpark — APPROVED** [review]

**Comment by Princesseuh** [comment]
File icons in VS Code are typically not white,
image
As you can see, the only white one is "no language"

**Review by Princesseuh — CHANGES_REQUESTED** [review]
see comment

**Comment by jasikpark** [comment]
Is the primary brand color of astro still orange? I'm not sure what it is?

**Review by Princesseuh — APPROVED** [review]

**Comment by Tc-001** [comment]
With the Astro file icon being white, how will it interact with the vscode light theme?

**Comment by natemoo-re** [comment]
> With the Astro file icon being white, how will it interact with the vscode light theme?

Great callout, fixed!

**Pull request merged**
