### PR TITLE
chore: add repository and update prettier-plugin-astro

### PR DESCRIPTION
**Pull request by lvqq**
## Changes
- Add  repository in package.json
- Update prettier-plugin-astro, refer: https://github.com/withastro/astro/issues/6803

### CODE REVIEW

**Comment by Princesseuh** [comment]
It seems like there's now 4 versions of the compiler in the lockfile, it'd be great to untangle that while we're there, as otherwise it won't fix the situation happening in main

**Comment by lvqq** [comment]
I agree. 

It could solve the issue in astro but will making things worse for this repository. What's the suggestion for this problem since there is a cycle in dependencies? 

@astro/language-server 0.29.6
  -> astro(devDependencies)
      -> @astro/language-server 0.28.3

And @astrojs/compiler is a direct dependency of @astro/language-server, is a indirect dependency of prettier-plugin-astro. For astro repository, a new version of @astro/language-server which depends on a v0.8.0 prettier-plugin-astro is needed

**Comment by ematipico** [comment]
@lvqq 

You have few options here. You could start by breaking down this PR into two PRs: 
- one where you just update the `package.json` fields, which are only metadata;
- another when where you tackle the update of the dependency;

Regarding the update of the dependency:  

```
@astro/language-server 0.29.6
-> astro(devDependencies)
-> @astro/language-server 0.28.3(dependencies)
```

You could make `astro(devDependencies)` a dev and **optional** dependency. Then you could add the [`peerDependenciesMeta`](https://pnpm.io/package_json#peerdependenciesmetaoptional) to tell the package manager that the dependency is not mandatory. **I think** that should help.

**Comment by Princesseuh** [comment]
I don't mind the devDeps at all actually. They're only used in tests to test that we get the types from Astro properly, so it doesn't really matter if we don't have a precise version for them. 

The main thing is avoiding multiple versions for users. Something to note is that `astro` cannot currently updates its `@astrojs/language-server` version until the later reaches 1.0 (https://github.com/withastro/language-tools/pull/482), because the versions of the package have diverged fairly consequentially.

Ideally, the path we'd take is the following:
- Release 1.0 of the Prettier plugin (https://github.com/withastro/prettier-plugin-astro/pull/329)
- Release 1.0 of the language-server (https://github.com/withastro/language-tools/pull/482), using the 1.0 of the Prettier plugin
- Both of them would use `^1.0.0` of `@astrojs/compiler`
- We update `astro` to use `^1.0.0` of the language-server

**Comment by lvqq** [comment]
@Princesseuh Thanks for your patient reply! I'd move the modification about the repository to another PR

**Pull request closed without merging**
