### PR TITLE
refactor(syntax): Use a YAML file to generate the final syntax

### PR DESCRIPTION
**Pull request by Princesseuh**
## Changes

Inspired by Svelte's language-tools, this moves our syntax file to a yaml file that is then converted to JSON for publishing. 

This has a lot of benefits:
- Much easier to author
- Much easier to read
- Allow us to use real comments

We kept the exact same feature set while using half as much lines

Fix https://github.com/withastro/language-tools/issues/459

## Testing

Updated snapshots to account for the changes

## Docs

N/A

### CODE REVIEW

**Review by matthewp — APPROVED** [review]
lgtm

**Comment by lildude** [comment]
👋 from GitHub's Linguist library which uses this grammar for syntax highlighting of Astro files on GitHub.com.

This PR has removed the `packages/vscode/syntaxes/astro.tmLanguage.json` file and hasn't replaced it with a version GitHub can use so we can no longer update the submodule to pull in your grammar changes.

**Comment by Princesseuh** [comment]
Hello! I'll add the built file to the repo aswell

**Comment by Princesseuh** [comment]
> 👋 from GitHub's Linguist library which uses this grammar for syntax highlighting of Astro files on GitHub.com.
> 
> This PR has removed the `packages/vscode/syntaxes/astro.tmLanguage.json` file and hasn't replaced it with a version GitHub can use so we can no longer update the submodule to pull in your grammar changes.

Fixed, sorry again for the inconvenience!

**Comment by lildude** [comment]
🎉 Perfect! Thanks for the quick fix.

**Pull request merged**
