### PR TITLE
feat: added icon to language

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can be helpful as well.

### CODE REVIEW

**Comment by JuanM04** [comment]
I've taken the icon from here: https://github.com/vscode-icons/vscode-icons/pull/2774

**Comment by antonyfaris** [comment]
> I've taken the icon from here: [vscode-icons/vscode-icons#2774](https://github.com/vscode-icons/vscode-icons/pull/2774)

The viewbox property has a different value. Maybe using the original size (32x32) will fix it?

**Comment by Princesseuh** [comment]
Unfortunately doesn't seem to change anything: 
image

**Comment by JuanM04** [comment]
Ok, I've found [this icon](https://github.com/withastro/astro/blob/main/assets/brand/file-icon.svg), maybe this one works

**Comment by Princesseuh** [comment]
Unfortunately, same thing with that one haha. Does it work fine on your side? Maybe it's an issue with my particular setup

**Comment by JuanM04** [comment]
I can replicate it but I don't know how to fix it. In only happens with the Seti theme, so maybe we could submit an icon there (?)

**Comment by JuanM04** [comment]
It seems that we aren't the only ones with alignment issues: https://github.com/microsoft/vscode/issues/141335#issuecomment-1021761492

**Review by natemoo-re — APPROVED** [review]
IMO a misaligned icon is better than no icon! I'd merge this and we can fix the alignment later?

**Comment by JuanM04** [comment]
@natemoo-re Let me do a quick try by removing the margins with figma. If it stays the same, I'll merge it

**Comment by JuanM04** [comment]
Plot twist: it didn't work

**Pull request merged**
