### PR TITLE
Add a new troubleshooting item about formatting

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
## Changes

- What does this change?
- Added a new troubleshooting entry about formatting `.astro` files because quite a few folks are having this [problem](https://x.com/PaulieScanlon/status/1701583756576858485?s=20)

## Testing

Yes Tested on vs code and other [folks](https://x.com/PaulieScanlon/status/1701583756576858485?s=20) tried it too
## Docs
No sure?

### CODE REVIEW

**Comment by Princesseuh** [comment]
Hmm, I don't see why this is necessary. On most setups, you won't have any other formatters enabled. The Astro extension will by default be used. What was your setup trying to use to format??

**Comment by Khaledgarbaya** [comment]
I installed the extension but didn't get auto formatting, for example on save, unless I add that to my settings.
I use prettier in vs code for formatting.

**Comment by Princesseuh** [comment]
> I installed the extension but didn't get auto formatting, for example on save, unless I add that to my settings. I use prettier in vs code for formatting.

Sure, but what extension was VS Code trying to use to format? VS Code uses the only formatter available if there's only one. Prettier does not advertise itself as being Astro compatible by default unless you configure it to do so, in which case it seems obvious to me that you need to make sure you're using the formatter you want (and VS Code will prompt you on format)

**Comment by Khaledgarbaya** [comment]
It was not very obvious for me and others. Prettier is wildly used by folks out there so I thought maybe it gets a special mention in the extension docs otherwise users will think that the extension is broken but I might be wrong.

**Comment by raae** [comment]
From the list below I felt like it should work out of the box, but it didn't and I got help from @Khaledgarbaya on Twitter via his answer to another person: https://x.com/PaulieScanlon/status/1704207301819662457?s=20
CleanShot 2023-09-20 at 21 48 33@2x

**Comment by Princesseuh** [comment]
Okay, I don't think I've made myself clear on what I'm asking 😅

What this configuration does is set the default formatter for Astro files to be the Astro extension. 

However: 
- If there's only one formatter for a file format, VS Code will use that formatter by default.
- No other extensions on the marketplace is compatible with Astro files, by default (Prettier's VS Code extension *can be*, if you specifically configure it to be)
- If for some reason, you have multiple formatters installed, but none are set as default, VS Code will prompt you to choose.

What this configuration does is simply reiterate the default behaviour of VS Code. As such, I don't understand *why* it would fix anything, nor why it would be necessary to have

**Comment by Khaledgarbaya** [comment]
Sounds Good, maybe something is wrong in our vs code configuration ¯\_(ツ)_/¯. Closing the PR, and thank you for your time

**Pull request closed without merging**
