### PR TITLE
fix: upgrade volarjs/services from v0.0.4 to v0.0.5

### PR DESCRIPTION
**Pull request by intagaming**
The published v0.0.4 (f5d4949) of volar-service-typescript causes error because it tries to access ctx.typescript.languageService; in fact it was `undefined`. After f5d4949, the v0.0.4 continues but no new version
of it was published on npmjs. v0.0.5 has just been released, in which the above problem was fixed. Some API changes were compensated for.

## Changes

- Version-bumping volar-service-* from `v0.0.4` to `v0.0.5`
- Upgrading @volar/* to `v1.7.0`
- Some API changes were compensated.

## Testing

Before: It errored, looks like this:
<details><summary>~/.local/state/nvim/lsp.log</summary>

```ts
[ERROR][2023-06-03 14:42:35] .../vim/lsp/rpc.lua:734    "rpc"   "/home/an7/.local/share/nvim/mason/bin/astro-ls"        "stderr"        "service typescript cr
ashed on file:///home/an7/files/dev/coccoc-astro/src/pages/search/index.astro.tsx TypeError: Cannot read properties of undefined (reading 'languageService')\n
    at /home/an7/.local/share/nvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/volar-service-typescript/out/servic
es/diagnostics.js:12:40\n    at Object.provideSemanticDiagnostics (/home/an7/.local/share/nvim/mason/packages/astro-language-server/node_modules/@astrojs/lang
uage-server/node_modules/volar-service-typescript/out/index.js:278:24)\n    at Object.provideSemanticDiagnostics (/home/an7/.local/share/nvim/mason/packages/a
stro-language-server/node_modules/@astrojs/language-server/dist/plugins/typescript/index.js:53:56)\n    at /home/an7/.local/share/nvim/mason/packages/astro-la
nguage-server/node_modules/@astrojs/language-server/node_modules/@volar/language-service/out/languageFeatures/validation.js:261:52\n    at /home/an7/.local/sh
are/nvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-service/out/utils/featureWorkers.js:23:65\n  
  at safeCall (/home/an7/.local/share/nvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-service/out
/utils/featureWorkers.js:133:22)\n    at /home/an7/.local/share/nvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@
volar/language-service/out/utils/featureWorkers.js:23:50\n    at async visitEmbedded (/home/an7/.local/share/nvim/mason/packages/astro-language-server/node_mo
dules/@astrojs/language-server/node_modules/@volar/language-service/out/utils/definePlugin.js:12:18)\n    at async visitEmbedded (/home/an7/.local/share/nvim/
mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-service/out/utils/definePlugin.js:6:14)\n    at async 
languageFeatureWorker (/home/an7/.local/share/nvim/mason/packages/astro-language-server/node_modules/@astrojs/language-server/node_modules/@volar/language-ser
vice/out/utils/featureWorkers.js:20:9)\n"
```
</details> 

Steps: Built it with `pnpm build`, then `npm pack`-ed the `language-server`. Went to `mason.nvim`'s `astro-language-server` installation and load the packed file into the `package.json`, then installed it.

After: The LSP in Neovim works, albeit with some settings about `typescript.tsdk` that must be set.

VSCode was not tested (I'm not a VSCode guru), though `pnpm test` was good.

## Docs

Public documentation was not updated and I believe that we don't need to, since this PR only touches internal stuff. The `typescript.tsdk` configuration was needed to run in Neovim though (since `@astrojs/language-server@2.0.0`), but that's for the `nvim-lspconfig` documentation.

### CODE REVIEW

**Comment by intagaming** [comment]
Hi maintainers. Something happened in the Windows CI, and frankly I don't understand one bit of it... Looks like a heap memory error or something?

**Comment by johnsoncodehk** [comment]
I also found windows CI failed in https://github.com/vuejs/language-tools/pull/3248, probably a regression of v1.7, pin v1.6.9 and services v0.0.4 should temporarily avoid the problem.

**Comment by intagaming** [comment]
> I also found windows CI failed in [vuejs/language-tools#3248](https://github.com/vuejs/language-tools/pull/3248), probably a regression of v1.7, pin v1.6.9 and services v0.0.4 should temporarily avoid the problem.

That would means this PR is on hold. Has you figured out why it happens?

**Comment by yaegassy** [comment]
@intagaming How about closing this PR and creating a new PR that adds the PIN?

- `"@volar/xxxx": "^1.6.9"` -> `"@volar/xxxx": "1.6.9"`
- `"volar-service-xxxx": "^0.0.4"` -> `"volar-service-xxxx": "0.0.4"`

**Comment by intagaming** [comment]
> @intagaming How about closing this PR and creating a new PR that adds the PIN?
> 
>     * `"@volar/xxxx": "^1.6.9"` -> `"@volar/xxxx": "1.6.9"`
> 
>     * `"volar-service-xxxx": "^0.0.4"` -> `"volar-service-xxxx": "0.0.4"`

v0.0.4 was broken and will cause the error in the original post, thus can't be used anymore. Is there anything that I missed or something? Do your config works with `0.0.4`?

**Comment by yaegassy** [comment]
The current issue is that the dependency "@volar/xxxx" is being installed as version 1.7.x, which causes problems. So I tried reinstalling it as version 1.6.9, and the language server started up without any errors.

**e.g.**:

```
$ mkdir -p /tmp/astrols-check
$ cd /tmp/astrols-check
$ npm init -y
$ npm i @astrojs/language-server
$ cat node_modules/@volar/language-server/package.json | grep "version"
	"version": "1.7.1",
$ cat node_modules/volar-service-typescript/package.json | grep "version"
	"version": "0.0.4",
$ # PIN Like
$ npm i @volar/language-server@1.6.9
$ cat node_modules/@volar/language-server/package.json | grep "version"
	"version": "1.6.9",
```

**Comment by intagaming** [comment]
I will try it again, but I'm pretty sure the git-head commit hash I checked the other day in the pulled package.json was bang-on v0.0.4, which assuming the npmjs package repository does its job, will definitely cause error. I will try one more time just to be absolutely sure.

**Comment by yaegassy** [comment]
I have also tried it in this repository itself. There are no errors in launching the language server or any issues behind the scenes after it starts, and it is working fine.

**1. Prepare**:

```
mkdir -p /tmp/astrols-check
cd /tmp/astrols-check
git clone git@github.com:withastro/language-tools.git
cd language-tools
```

**2. Change packages/language-server/package.json**:

> I will fix it to version 1.6.9.

```
{
  // ...snip
    "@volar/kit": "1.6.9",
    "@volar/language-core": "1.6.9",
    "@volar/language-server": "1.6.9",
    "@volar/language-service": "1.6.9",
    "@volar/source-map": "1.6.9",
  // ...snip
}
```

**3. Install and build**:

```
pnpm i
pnpm build

cat packages/language-server/node_modules/@volar/language-server/package.json  | grep "version"
	"version": "1.6.9",
cat packages/language-server/node_modules/volar-service-typescript/package.json  | grep "version"
	"version": "0.0.4",
```

**Comment by johnsoncodehk** [comment]
> That would means this PR is on hold. Have you figured out why it happens?

Not yet, I'm trying to investigate but the error is the same.

**Pull request closed without merging**
