### PR TITLE
Updated TypeScript from 4.6.0 to 4.8.2

### PR DESCRIPTION
**Pull request by jonathantneal**
## Changes

- This updates the TypeScript dependencies from 4.6.0 to 4.8.2
- Starting in TypeScript 4.7.x, [`package.json` exports are supported](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing).
- During `build`, I noticed a missing interface for `InlayHintsOptions`, which was then added with citation from the TypeScript Fourslash suite.

## Testing

Followed CONTRIBUTING.md.

## Docs

dependency update only

### CODE REVIEW

**Comment by Princesseuh** [comment]
Hello! Thank you for this PR. Unfortunately, updating to the latest TypeScript version is not that easy. 

Some changes to our module resolution cache and our code actions are needed to properly support 4.7. Additionally, our current language services force `moduleResolution` to `node` which is not ideal

**Comment by jonathantneal** [comment]
Thanks for the quick review, @Princesseuh. To clarify, would the guidance be to apply similar kinds of changes as https://github.com/sveltejs/language-tools/pull/1526? I want to be sure I’m looking at the right change Svelte made. If you’re not sure, I can ask later this week, too. No rush, and again, thank you for the incredibly fast review.

**Comment by Princesseuh** [comment]
> Thanks for the quick review, @Princesseuh. To clarify, would the guidance be to apply similar kinds of changes as https://github.com/sveltejs/language-tools/pull/1526? I want to be sure I’m looking at the right change Svelte made. If you’re not sure, I can ask later this week, too. No rush, and again, thank you for the incredibly fast review.

Yep! That's the right PR. Additionally, support for group aware organize imports should be considered for full support  https://github.com/sveltejs/language-tools/pull/1515

I'm okay with that one being tackled separately if you prefer not to, it's alright. I can tackle it myself låter

**Comment by Princesseuh** [comment]
https://github.com/withastro/language-tools/pull/389 makes this PR unnecessary. We'll still need to add support for `node16` resolution and group aware imports, but it'll be tackled separately. Thank you for making this PR!

**Pull request closed without merging**
