### PR TITLE
Refactor tmLanguage declarations

### LINKED ISSUE #165: 🐛 BUG: Invalid Regex
### Describe the Bug

When I was trying to add the new grammar definitions to GitHub linguist, it threw these errors:

```
2 errors found in new grammar 'repository `vendor/grammars/astro` (from https://github.com/withastro/language-tools.git)':
- Invalid regex in grammar: `text.html.astro` (in `packages/vscode/syntaxes/astro.tmLanguage.json`) contains a malformed regex (regex "`(?<=<(?i:script)[^>]*>)(?!\G)`": lookbehind assertion is not fixed length (at offset 22))
- Invalid regex in grammar: `text.html.astro` (in `packages/vscode/syntaxes/astro.tmLanguage.json`) contains a malformed regex (regex "`(?<=<(?i:style)[^>]*>)(?!\G)`": lookbehind assertion is not fixed length (at offset 21))
```

### Steps to Reproduce

1. Setup github/linguist
2. Run `script/add-grammar --replace astro https://github.com/withastro/language-tools`

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

fixes #165

- [x] Removed lookbehinds with not fixed length
- [x] Remove astro markdown and only use the inject

A lot of the improvements where based of [the work made by the Svelte team](https://github.com/sveltejs/language-tools)

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
I don't grok all of this, but I trust you! Thanks for tackling this!

**Comment by natemoo-re** [comment]
Will this close https://github.com/withastro/astro/pull/2516 ?

**Comment by JuanM04** [comment]
@natemoo-re Not yet. First, I'll need to to submit a PR to github linguist and then that PR can get merged

**Comment by jasikpark** [comment]
@JuanM04 if you use VScode there's a very useful extension for validating tmLanguage files

**Comment by FredKSchott** [comment]
Nice! I just took this for a spin locally following these instructions: https://www.codemag.com/article/1809051/Writing-Your-Own-Debugger-and-Language-Extensions-with-Visual-Studio-Code

And every astro file that I opened in VSCode looked good!

**Pull request merged**
